deploy test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,14 +11,21 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # Извлекаем репозиторий из папки $GITHUB_WORKSPACE
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
+      # Устанавливаем Node.js 
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
         with:
-          node-version: '22'
+          node-version: '22.14.0'
 
+      # Устанавливаем зависимости
+      - name: Install Dependencies
+        run: npm ci
+
+      # Устанавливаем переменные из секретов репозитория
       - name: Set environment variables
         run: |
           echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" >> $GITHUB_ENV
@@ -29,27 +36,26 @@ jobs:
           echo "JWT_ACCESS_MAX_AGE=${{ secrets.JWT_ACCESS_MAX_AGE }}" >> $GITHUB_ENV
           echo "JWT_REFRESH_MAX_AGE=${{ secrets.JWT_REFRESH_MAX_AGE }}" >> $GITHUB_ENV
 
-      - name: Install dependencies
-        run: npm install
 
+      # Собираем проект
       - name: Build
         run: npm run Build
 
-      - name: Set up SSH key
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.PRODUCTION_SERVER_DEPLOY_KEY }}" > ~/.ssh/id_rsa_cloud || { echo "Failed to write SSH key"; exit 1; }
-          chmod 600 ~/.ssh/id_rsa_cloud
-          ssh-keyscan -H cloud.pas-gw.keenetic.pro >> ~/.ssh/known_hosts || { echo "Failed to add known hosts"; exit 1; }
-          cat ~/.ssh/known_hosts  # вывод содержимого known_hosts для отладки
+#      - name: Setup SSH key
+#        run: |
+#          mkdir -p ~/.ssh
+#          echo "${{ secrets.PRODUCTION_SERVER_DEPLOY_KEY }}" > ~/.ssh/id_rsa_cloud || { echo "Failed to write SSH key"; exit 1; }
+#          chmod 600 ~/.ssh/id_rsa_cloud
+#          ssh-keyscan -H cloud.pas-gw.keenetic.pro >> ~/.ssh/known_hosts || { echo "Failed to add known hosts"; exit 1; }
+#          cat ~/.ssh/known_hosts  # вывод содержимого known_hosts для отладки
 
-      - name: Test SSH connection
-        run: ssh -i ~/.ssh/id_rsa_cloud poe@cloud.pas-gw.keenetic.pro "echo 'SSH Connection Successful'"
+#      - name: Test SSH connection
+#        run: ssh -i ~/.ssh/id_rsa_cloud poe@cloud.pas-gw.keenetic.pro "echo 'SSH Connection Successful'"
 
-      - name: Create deploy directory
-        run: ssh -i ~/.ssh/id_rsa_cloud poe@cloud.pas-gw.keenetic.pro "mkdir -p ~/cloud_app"
+#      - name: Create deploy directory
+#        run: ssh -i ~/.ssh/id_rsa_cloud poe@cloud.pas-gw.keenetic.pro "mkdir -p ~/cloud_app"
 
-      - name: Deploy to server
-        run: |
-          rsync -r --delete --exclude=.git ./ poe@cloud.pas-gw.keenetic.pro:~/cloud_app
-          ssh -i ~/.ssh/id_rsa_cloud poe@cloud.poe-gw.keenetic.pro "cd ~/cloud_app && npm install --production && pm2 restart cloud_app"
+#      - name: Deploy to server
+#        run: |
+#          rsync -r --delete --exclude=.git ./ poe@cloud.pas-gw.keenetic.pro:~/cloud_app
+#          ssh -i ~/.ssh/id_rsa_cloud poe@cloud.poe-gw.keenetic.pro "cd ~/cloud_app && npm install --production && pm2 restart cloud_app"
